@startuml
!theme aws-orange

'Comment following line before commit
'!$approach = "luhmann"

!$label ?= { 
    "purpose": "Purpose", 
    "container1": "Container 1", 
    "container2": "Container 2",
    "inbox": "Inbox"
    } 

!if ($approach == "luhmann")
!$label = {
    "purpose": "Writing",
    "container1": "Reference Notes",
    "container2": "Permanent Notes",
    "inbox": "Floating Notes"
    }
!endif

rectangle $label.purpose as Purpose

' subgraph for alignment with surrounding nodes
' cf. http://www.forum.plantuml.net/10464/component-arrows-starting-wrong-side-component-components
cloud Brain #white [
External Brain
{{
    folder "$label.container2" as c2 {
        label c2.1 as "<size:30><&document></size>"
        label c2.2 as "<size:30><&document></size>"
        label c2.3 as "<size:30><&document></size>"
    }

    folder "$label.container1" as c1 {
        label c1.1 as "<size:30><&document></size>"
    }

    label free1 as "<size:30><&document></size>"

    c2.1 -> c1.1
    c1.1 -> c2.3
    c2.2 -> free1
    free1 -> c1.1
    c1.1 -> free1
}}
] 

folder "$label.inbox" as Inbox

together {
    rectangle Trash
    database Archive
}

' Formating help
Archive -[hidden]d-> Trash
'Purpose -[hidden]d-> Inbox

rectangle "Source 1" as Source1
rectangle "Source 2" as Source2
rectangle "Source n" as Source3


Brain -r-> Archive
Inbox -r-> Trash
Purpose -d-> Brain
Inbox -u-> Brain

Source1 -u-> Inbox
Source2 -u-> Inbox
Source3 -u-> Inbox

@enduml