@startuml overview
!theme aws-orange

skinparam BackgroundColor white

'Comment following line before commit
'!$approach = "para"

!$label ?= { 
    "purpose": "Purpose", 
    "container1": "Container 1", 
    "container2": "Container 2",
    "container3": "Container n",
    "inbox": "Inbox",
    "source1": "Source 1"
    } 

!$style_workflow = "dashed,thickness=7"
!$style_connection = "norank,thickness=2"


!if ($approach == "luhmann")
!$label = {
    "purpose": "Writing",
    "container1": "Project Notes",
    "container2": "Permanent Notes",
    "container3": "Reference Notes",
    "inbox": "Floating Notes",
    "source1": "Text <u><back:yellow>excerpts</back> from books</u>, articles etc."
    }
!elseif ($approach == "para")
!$label = {
    "purpose": "Learning",
    "container1": "Projects",
    "container2": "Areas",
    "container3": "Resources",
    "inbox": "Inbox",
    "source1": "Text <u><back:yellow>excerpts</back> from books</u>, articles etc."
    }
!endif

rectangle "$label.purpose" as Purpose

' subgraph for alignment with surrounding nodes
' cf. http://www.forum.plantuml.net/10464/component-arrows-starting-wrong-side-component-components
collections Brain [
External Brain
{{
    folder "$label.container2" as c2 {
        label "<size:30><&document></size>" as c2.1
        label "<size:30><&document></size>" as c2.2
        label "<size:30><&document></size>" as c2.3
    }

    folder "$label.container1" as c1 {
        label "<size:30><&document></size>" as c1.1
    }

    '!if ($label.container3)
    folder "$label.container3" as c3 {
        label "<size:30><&document></size>" as c3.1
        'file " " as c3.2
    }
    !if ($approach != "luhmann")
        c3 <-[$style_workflow]> c2
    !endif
    '!endif

    c1 <-[$style_workflow]> c2

    c2.1 -[$style_connection]-> c1.1
    c1.1 -[$style_connection]-> c2.3

    'label "<size:30><&document></size>" as free1
    'c2.2 -[$style_connection]-> free1
    'c1.1 -[$style_connection]-> free1
    'free1 -[$style_connection]-> c1.1
}}
] 

folder "$label.inbox" as Inbox

'together {
    rectangle Trash
    folder Archive
'}
' Formating help
'Archive -[hidden]d-> Trash

skinparam WrapWidth 100 

artifact "$label.source1" as Source1
artifact "Source 2" as Source2
artifact "Source n" as Source3


Brain -[$style_workflow]r-> Archive
Inbox -[$style_workflow]r-> Trash
Brain -[$style_workflow]u-> Purpose 
Inbox -[$style_workflow]u-> Brain

Source1 -[$style_workflow]u-> Inbox
Source2 -[$style_workflow]u-> Inbox
Source3 -[$style_workflow]u-> Inbox

'Interaction steps at right side 
together {
    label "**Interaction**" as level_purpose
    label "connect & maintain" as level_brain
    label "condense & enrich" as level_inbox
    label "discover" as level_source
}

Purpose -[norank,hidden]r-> level_purpose
Brain -[norank,hidden]r-> level_brain
Inbox -[norank,hidden]r-> level_inbox
Source1 -[norank,hidden]r-> level_source

level_purpose -[dotted]d- level_brain : access 
level_brain -[dotted]d- level_inbox : store
level_inbox -[dotted]d- level_source : collect

@enduml